# Change these first
owner: thedgden # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Digital Den Website
    url: $MAIN_SITE
  - name: Digital Den Panel
    url: $PANEL_SITE
  - name: Digital Den Status
    url: $STATUS_SITE
  - name: RostaBot Website
    url: $ROSTABOT_SITE
  - name: RostaBot
    url: $ROSTABOT_BOT
    port: $ROSTABOT_BOT_PORT
    check: "tcp-ping"
  - name: WastedRZ Website
    url: $WASTEDRZ_SITE
  - name: WastedRZ (FiveM)
    url: $WASTEDRZ_FIVEM
    port: $WASTEDRZ_FIVEM_PORT
    check: "tcp-ping"
  - name: GitHub Bot
    url: $GHBOT_BOT
    port: $GHBOT_BOT_PORT
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dgden.com
  theme: night
  delay: 30000 # 30 seconds
  # baseUrl: /your-repo-name
  name: Digital Den Status Page
  logoUrl: https://dgden.com/images/digitalden.png
  favicon: https://dgden.com/images/digitalden.png
  introTitle: "**Digital Den Status Portal**"
  introMessage: Here you can monitor the uptime and performance of our various platforms.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://dgden.com

i18n:
  footer: Digital Den © 2025

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
